//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Log.
        /// </summary>
        public static string Access_Log {
            get {
                return ResourceManager.GetString("Access Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Rights.
        /// </summary>
        public static string Access_Rights {
            get {
                return ResourceManager.GetString("Access Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string Add_User {
            get {
                return ResourceManager.GetString("Add User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Value.
        /// </summary>
        public static string Additional_Value {
            get {
                return ResourceManager.GetString("Additional Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Only.
        /// </summary>
        public static string Admin_Only {
            get {
                return ResourceManager.GetString("Admin Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All System Icon.
        /// </summary>
        public static string All_System_Icon {
            get {
                return ResourceManager.GetString("All System Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Text.
        /// </summary>
        public static string Alternate_Text {
            get {
                return ResourceManager.GetString("Alternate Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please contact administrator..
        /// </summary>
        public static string An_error_occurred__Please_contact_administrator_ {
            get {
                return ResourceManager.GetString("An error occurred. Please contact administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching tree data..
        /// </summary>
        public static string An_error_occurred_while_fetching_tree_data_ {
            get {
                return ResourceManager.GetString("An error occurred while fetching tree data.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the file..
        /// </summary>
        public static string An_error_occurred_while_uploading_the_file_ {
            get {
                return ResourceManager.GetString("An error occurred while uploading the file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        public static string Assign_To {
            get {
                return ResourceManager.GetString("Assign To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel.
        /// </summary>
        public static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel Name.
        /// </summary>
        public static string Carousel_Name {
            get {
                return ResourceManager.GetString("Carousel Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        public static string Check_in {
            get {
                return ResourceManager.GetString("Check in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In/Out.
        /// </summary>
        public static string Check_In_Out {
            get {
                return ResourceManager.GetString("Check In/Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Check_Out {
            get {
                return ResourceManager.GetString("Check Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Access Icon Library..
        /// </summary>
        public static string Click_To_Access_Icon_Library_ {
            get {
                return ResourceManager.GetString("Click To Access Icon Library.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Configuration.
        /// </summary>
        public static string Code_Configuration {
            get {
                return ResourceManager.GetString("Code Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Colour {
            get {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Icon.
        /// </summary>
        public static string Company_Icon {
            get {
                return ResourceManager.GetString("Company Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name.
        /// </summary>
        public static string Configuration_Name {
            get {
                return ResourceManager.GetString("Configuration Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Matrix Tree.
        /// </summary>
        public static string Copy_Matrix_Tree {
            get {
                return ResourceManager.GetString("Copy Matrix Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Matrix Tree.
        /// </summary>
        public static string Create_Matrix_Tree {
            get {
                return ResourceManager.GetString("Create Matrix Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Matrix Tree.
        /// </summary>
        public static string Cut_Matrix_Tree {
            get {
                return ResourceManager.GetString("Cut Matrix Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string Date_Format {
            get {
                return ResourceManager.GetString("Date Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Carousel.
        /// </summary>
        public static string Default_Carousel {
            get {
                return ResourceManager.GetString("Default Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Matrix Tree.
        /// </summary>
        public static string Delete_Matrix_Tree {
            get {
                return ResourceManager.GetString("Delete Matrix Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string Device_Name {
            get {
                return ResourceManager.GetString("Device Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Display_Name {
            get {
                return ResourceManager.GetString("Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download sample.
        /// </summary>
        public static string Download_sample {
            get {
                return ResourceManager.GetString("Download sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string Export_CSV {
            get {
                return ResourceManager.GetString("Export CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string Export_Excel {
            get {
                return ResourceManager.GetString("Export Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string Export_PDF {
            get {
                return ResourceManager.GetString("Export PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Reference.
        /// </summary>
        public static string External_Reference {
            get {
                return ResourceManager.GetString("External Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch tree data..
        /// </summary>
        public static string Failed_to_fetch_tree_data_ {
            get {
                return ResourceManager.GetString("Failed to fetch tree data.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtered from.
        /// </summary>
        public static string filtered_from {
            get {
                return ResourceManager.GetString("filtered from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string General_Information {
            get {
                return ResourceManager.GetString("General Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated on.
        /// </summary>
        public static string Generated_on {
            get {
                return ResourceManager.GetString("Generated on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geomerty Data.
        /// </summary>
        public static string Geomerty_Data {
            get {
                return ResourceManager.GetString("Geomerty Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Param.
        /// </summary>
        public static string Global_Param {
            get {
                return ResourceManager.GetString("Global Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HasAddi.
        /// </summary>
        public static string HasAddi {
            get {
                return ResourceManager.GetString("HasAddi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Not found.
        /// </summary>
        public static string Image_Not_found {
            get {
                return ResourceManager.GetString("Image Not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        public static string Invalid_date {
            get {
                return ResourceManager.GetString("Invalid date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Testing.
        /// </summary>
        public static string Is_Testing {
            get {
                return ResourceManager.GetString("Is Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Visible.
        /// </summary>
        public static string Is_Visible {
            get {
                return ResourceManager.GetString("Is Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look Up Type.
        /// </summary>
        public static string Look_Up_Type {
            get {
                return ResourceManager.GetString("Look Up Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look Up Value.
        /// </summary>
        public static string Look_Up_Value {
            get {
                return ResourceManager.GetString("Look Up Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string MAC_Address {
            get {
                return ResourceManager.GetString("MAC Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string Main_Menu {
            get {
                return ResourceManager.GetString("Main Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix Tree Manual.
        /// </summary>
        public static string Matrix_Tree_Manual {
            get {
                return ResourceManager.GetString("Matrix Tree Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCA/VCA.
        /// </summary>
        public static string MCA_VCA {
            get {
                return ResourceManager.GetString("MCA/VCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string Mobile_No {
            get {
                return ResourceManager.GetString("Mobile No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        public static string Modify_User {
            get {
                return ResourceManager.GetString("Modify User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Format.
        /// </summary>
        public static string Month_Format {
            get {
                return ResourceManager.GetString("Month Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Company.
        /// </summary>
        public static string Name_of_Company {
            get {
                return ResourceManager.GetString("Name of Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string No_data_available {
            get {
                return ResourceManager.GetString("No data available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othername.
        /// </summary>
        public static string Othername {
            get {
                return ResourceManager.GetString("Othername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding No.
        /// </summary>
        public static string Padding_No {
            get {
                return ResourceManager.GetString("Padding No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Task.
        /// </summary>
        public static string Parent_Task {
            get {
                return ResourceManager.GetString("Parent Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Matrix Tree.
        /// </summary>
        public static string Paste_Matrix_Tree {
            get {
                return ResourceManager.GetString("Paste Matrix Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Day.
        /// </summary>
        public static string Planned_Day {
            get {
                return ResourceManager.GetString("Planned Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Duration.
        /// </summary>
        public static string Please_Enter_Duration {
            get {
                return ResourceManager.GetString("Please Enter Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Sequence.
        /// </summary>
        public static string Please_Enter_Sequence {
            get {
                return ResourceManager.GetString("Please Enter Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Task Name.
        /// </summary>
        public static string Please_Enter_Task_Name {
            get {
                return ResourceManager.GetString("Please Enter Task Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill In Mandatory Fields.
        /// </summary>
        public static string Please_Fill_In_Mandatory_Fields {
            get {
                return ResourceManager.GetString("Please Fill In Mandatory Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in required field(s).
        /// </summary>
        public static string Please_fill_in_required_field_s_ {
            get {
                return ResourceManager.GetString("Please fill in required field(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Parent Task.
        /// </summary>
        public static string Please_Parent_Task {
            get {
                return ResourceManager.GetString("Please Parent Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select File.
        /// </summary>
        public static string Please_Select_File {
            get {
                return ResourceManager.GetString("Please Select File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Map.
        /// </summary>
        public static string Please_select_Map {
            get {
                return ResourceManager.GetString("Please select Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Proper Poster..!.
        /// </summary>
        public static string Please_select_Proper_Poster___ {
            get {
                return ResourceManager.GetString("Please select Proper Poster..!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the Icon.
        /// </summary>
        public static string Please_Select_the_Icon {
            get {
                return ResourceManager.GetString("Please Select the Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a valid file in one of the following formats: JPEG, or PNG..
        /// </summary>
        public static string Please_upload_a_valid_file_in_one_of_the_following_formats__JPEG__or_PNG_ {
            get {
                return ResourceManager.GetString("Please upload a valid file in one of the following formats: JPEG, or PNG.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Postal_Code {
            get {
                return ResourceManager.GetString("Postal Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster Name.
        /// </summary>
        public static string Poster_Name {
            get {
                return ResourceManager.GetString("Poster Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string Profile_Image {
            get {
                return ResourceManager.GetString("Profile Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code.
        /// </summary>
        public static string Project_Code {
            get {
                return ResourceManager.GetString("Project Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ColorCode.
        /// </summary>
        public static string Project_ColorCode {
            get {
                return ResourceManager.GetString("Project ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string Project_Description {
            get {
                return ResourceManager.GetString("Project Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string Project_Details {
            get {
                return ResourceManager.GetString("Project Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string Project_Manager {
            get {
                return ResourceManager.GetString("Project Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Matrix.
        /// </summary>
        public static string Project_Matrix {
            get {
                return ResourceManager.GetString("Project Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Template.
        /// </summary>
        public static string Project_Template {
            get {
                return ResourceManager.GetString("Project Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project View.
        /// </summary>
        public static string ProjectView {
            get {
                return ResourceManager.GetString("ProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string Registration_Date {
            get {
                return ResourceManager.GetString("Registration Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string Registration_Number {
            get {
                return ResourceManager.GetString("Registration Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Matrix Tree.
        /// </summary>
        public static string Rename_Matrix_Tree {
            get {
                return ResourceManager.GetString("Rename Matrix Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Image.
        /// </summary>
        public static string Report_Image {
            get {
                return ResourceManager.GetString("Report Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Config.
        /// </summary>
        public static string Reset_Config {
            get {
                return ResourceManager.GetString("Reset Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Location.
        /// </summary>
        public static string Room_Location {
            get {
                return ResourceManager.GetString("Room Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name.
        /// </summary>
        public static string Room_Name {
            get {
                return ResourceManager.GetString("Room Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        public static string Room_Type {
            get {
                return ResourceManager.GetString("Room Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successful.
        /// </summary>
        public static string Save_Successful {
            get {
                return ResourceManager.GetString("Save Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a Zone....
        /// </summary>
        public static string Search_for_a_Zone___ {
            get {
                return ResourceManager.GetString("Search for a Zone...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AssignTo.
        /// </summary>
        public static string Select_AssignTo {
            get {
                return ResourceManager.GetString("Select AssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company.
        /// </summary>
        public static string Select_Company {
            get {
                return ResourceManager.GetString("Select Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Configuration.
        /// </summary>
        public static string Select_Configuration {
            get {
                return ResourceManager.GetString("Select Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        public static string Select_Project {
            get {
                return ResourceManager.GetString("Select Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project Template.
        /// </summary>
        public static string Select_Project_Template {
            get {
                return ResourceManager.GetString("Select Project Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Purpose.
        /// </summary>
        public static string Select_Purpose {
            get {
                return ResourceManager.GetString("Select Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Resource.
        /// </summary>
        public static string Select_Resource {
            get {
                return ResourceManager.GetString("Select Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string Select_Role {
            get {
                return ResourceManager.GetString("Select Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        public static string Select_Room {
            get {
                return ResourceManager.GetString("Select Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string Select_Status {
            get {
                return ResourceManager.GetString("Select Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string Select_Type {
            get {
                return ResourceManager.GetString("Select Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence already Added.
        /// </summary>
        public static string Sequence_already_Added {
            get {
                return ResourceManager.GetString("Sequence already Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Details.
        /// </summary>
        public static string Status_Details {
            get {
                return ResourceManager.GetString("Status Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Menu.
        /// </summary>
        public static string Sub_Menu {
            get {
                return ResourceManager.GetString("Sub Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Icon.
        /// </summary>
        public static string System_Icon {
            get {
                return ResourceManager.GetString("System Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Code Configuration.
        /// </summary>
        public static string Table_Code_Configuration {
            get {
                return ResourceManager.GetString("Table Code Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        public static string Table_Name {
            get {
                return ResourceManager.GetString("Table Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Code.
        /// </summary>
        public static string Task_Code {
            get {
                return ResourceManager.GetString("Task Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Description.
        /// </summary>
        public static string Task_Description {
            get {
                return ResourceManager.GetString("Task Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string Task_Name {
            get {
                return ResourceManager.GetString("Task Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name already Added.
        /// </summary>
        public static string Task_Name_already_Added {
            get {
                return ResourceManager.GetString("Task Name already Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string Telephone_Number {
            get {
                return ResourceManager.GetString("Telephone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Count.
        /// </summary>
        public static string Test_Count {
            get {
                return ResourceManager.GetString("Test Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Geomerty Data.
        /// </summary>
        public static string Test_Geomerty_Data {
            get {
                return ResourceManager.GetString("Test Geomerty Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Code.
        /// </summary>
        public static string Testing_Code {
            get {
                return ResourceManager.GetString("Testing Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Date.
        /// </summary>
        public static string Testing_Date {
            get {
                return ResourceManager.GetString("Testing Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Image.
        /// </summary>
        public static string Testing_Image {
            get {
                return ResourceManager.GetString("Testing Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Name.
        /// </summary>
        public static string Testing_Name {
            get {
                return ResourceManager.GetString("Testing Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Type.
        /// </summary>
        public static string Testing_Type {
            get {
                return ResourceManager.GetString("Testing Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size exceeds the allowed limit of 2MB..
        /// </summary>
        public static string The_file_size_exceeds_the_allowed_limit_of_2MB_ {
            get {
                return ResourceManager.GetString("The file size exceeds the allowed limit of 2MB.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string Time_Zone {
            get {
                return ResourceManager.GetString("Time Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree View.
        /// </summary>
        public static string Tree_View {
            get {
                return ResourceManager.GetString("Tree View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string Upload_File {
            get {
                return ResourceManager.GetString("Upload File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsePrefix.
        /// </summary>
        public static string UsePrefix {
            get {
                return ResourceManager.GetString("UsePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Matrix.
        /// </summary>
        public static string User_Matrix {
            get {
                return ResourceManager.GetString("User Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Name.
        /// </summary>
        public static string View_Name {
            get {
                return ResourceManager.GetString("View Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        public static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Format.
        /// </summary>
        public static string Year_Format {
            get {
                return ResourceManager.GetString("Year Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Management.
        /// </summary>
        public static string Zone_Management {
            get {
                return ResourceManager.GetString("Zone Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Matrix.
        /// </summary>
        public static string Zone_Matrix {
            get {
                return ResourceManager.GetString("Zone Matrix", resourceCulture);
            }
        }
    }
}
