using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL.Models.Administration
{
    public class SYS_Modules : BaseAuditModel, IAuditable
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(120, ErrorMessage = "Name cannot exceed 120 characters. ")]
        public string? Name { get; set; }
        public string? DisplayName { get; set; }
        public string? Icon { get; set; }
        public int Order { get; set; }
        public Guid? ParentId { get; set; } = null;
        public string? Url { get; set; }
        public bool? HasAutoGeneratedCode { get; set; } = false;
    }
}
